name: Pull Request Locally Test Merge Into main

on:
  pull_request:
    branches:
      - main

jobs:
  buildTestBaseImageDebian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Environment Variables
        run: printenv
      - name: Build Docker Image
        id: build_docker_image
        run: docker build --tag docker-base-image-debian:${GITHUB_HEAD_REF:-${GITHUB_REF##*/}} .

